export const products = [
  {
    id: 'ramudishi',
    name: 'Ramudishi',
    category: 'Wines & Spirits',
    subcategory: 'Local spirits',
    price: 55000,
    size: '750ml bottle',
    badge: 'Premium Pick',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A premium shelf bottle positioned for special gatherings and gift-ready orders.',
    benefits: ['Popular for events', 'Elegant bottle presentation', 'Ideal for chilled serving'],
    ingredients: 'Spirit blend',
    instructions: 'Ask the shop for current stock and serving recommendations.',
  },
  {
    id: 'ibisorori',
    name: 'Ibisorori',
    category: 'Wines & Spirits',
    subcategory: 'Local spirits',
    price: 50000,
    size: '750ml bottle',
    badge: 'Celebration Choice',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A festive bottle selected for home celebrations, hosting, and weekend stock-up.',
    benefits: ['Good for sharing', 'Classic bottle format', 'Easy to pair with snacks'],
    ingredients: 'Spirit blend',
    instructions: 'Serve cold for the best experience.',
  },
  {
    id: 'crystal',
    name: 'Crystal',
    category: 'Beer & Cider',
    subcategory: 'Beer',
    price: 43000,
    size: 'Crate / bulk order',
    badge: 'Fast Moving',
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A reliable beer option for everyday refreshment and group occasions.',
    benefits: ['Easy party option', 'Great for chilled service', 'Regular customer favorite'],
    ingredients: 'Malted beverage',
    instructions: 'Best served cold.',
  },
  {
    id: 'drosty-5l',
    name: 'Drosty 5l',
    category: 'Wines & Spirits',
    subcategory: 'Box wine',
    price: 40000,
    size: '5 litre pack',
    badge: 'Family Size',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A value-focused 5 litre option designed for larger gatherings and home stock.',
    benefits: ['Large format', 'Good value per litre', 'Convenient for events'],
    ingredients: 'Wine blend',
    instructions: 'Keep upright and chill after opening.',
  },
  {
    id: 'tuska',
    name: 'Tuska',
    category: 'Beer & Cider',
    subcategory: 'Beer',
    price: 30000,
    size: 'Crate / bulk order',
    badge: 'Weekend Favorite',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A crowd-friendly beer choice kept for casual hosting and retail take-away.',
    benefits: ['Popular with groups', 'Easy to chill and serve', 'Solid value'],
    ingredients: 'Malted beverage',
    instructions: 'Request crate availability from the shop.',
  },
  {
    id: 'umushonjye-munini',
    name: 'Umushonjye munini',
    category: 'Beer & Cider',
    subcategory: 'Beer',
    price: 28500,
    size: 'Large bottle pack',
    badge: 'Large Format',
    image: 'https://images.unsplash.com/photo-1567696911980-2c5d2c88f0a4?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'Large-format bottle stock for customers who want more volume per purchase.',
    benefits: ['Larger serving size', 'Good for sharing', 'Budget-friendly format'],
    ingredients: 'Malted beverage',
    instructions: 'Serve cold.',
  },
  {
    id: 'nido-medium',
    name: 'Nido medium',
    category: 'Milk & Baby',
    subcategory: 'Milk powder',
    price: 27000,
    size: 'Medium tin',
    badge: 'Household Staple',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'Milk powder kept for family breakfast routines and daily kitchen use.',
    benefits: ['Easy to store', 'Useful for tea and porridge', 'Popular repeat purchase'],
    ingredients: 'Fortified milk powder',
    instructions: 'Store in a dry place and close tightly after opening.',
  },
  {
    id: 'tasker',
    name: 'Tasker',
    category: 'Beer & Cider',
    subcategory: 'Beer',
    price: 27000,
    size: 'Crate / bulk order',
    badge: 'Top Seller',
    image: 'https://images.unsplash.com/photo-1571767454098-246b94fbcf70?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A familiar beer line for customers buying for home, parties, and social events.',
    benefits: ['Recognizable brand style', 'Suitable for bulk purchase', 'Best chilled'],
    ingredients: 'Malted beverage',
    instructions: 'Ask for crate and bottle availability.',
  },
  {
    id: 'simirnoff-ice',
    name: 'Simirnoff ice',
    category: 'Beer & Cider',
    subcategory: 'Cider',
    price: 27000,
    size: 'Bottle pack',
    badge: 'Ready To Drink',
    image: 'https://www.felipemotta.store/media/catalog/product/cache/214/image/1000x/040ec09b1e35df139433887a97daa66f/s/m/smirnoff_ice_long_neck_275ml.jpg',
    extraImages: [],
    description: 'A chilled ready-to-drink option with a smooth, refreshing finish.',
    benefits: ['Easy to serve', 'Great for casual occasions', 'Customer-friendly flavor'],
    ingredients: 'Flavored alcoholic beverage',
    instructions: 'Serve very cold.',
  },
  {
    id: 'inzoga-simirnoff',
    name: 'Inzoga simirnoff',
    category: 'Wines & Spirits',
    subcategory: 'Flavored spirit',
    price: 27000,
    size: 'Bottle',
    badge: 'Party Pick',
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A colorful bottle choice aimed at nightlife orders and party tables.',
    benefits: ['Eye-catching presentation', 'Good for parties', 'Simple take-away choice'],
    ingredients: 'Flavored spirit',
    instructions: 'Chill before serving.',
  },
  {
    id: 'sabroso-oil-nini',
    name: 'Sabroso oil nini',
    category: 'Cooking Essentials',
    subcategory: 'Cooking oil',
    price: 24000,
    size: 'Large bottle',
    badge: 'Kitchen Essential',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A large-format cooking oil option for homes, food prep, and daily frying needs.',
    benefits: ['Large capacity', 'Practical for daily cooking', 'Useful for family kitchens'],
    ingredients: 'Vegetable oil',
    instructions: 'Store away from direct sunlight.',
  },
  {
    id: 'amata-yifu-yinyange-1kg',
    name: 'Amata yifu yinyange 1kg',
    category: 'Milk & Baby',
    subcategory: 'Milk powder',
    price: 20000,
    size: '1kg pack',
    badge: 'Local Favorite',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A practical 1kg milk powder pack for tea, porridge, and family use.',
    benefits: ['Good kitchen size', 'Easy to keep on shelf', 'Useful for many recipes'],
    ingredients: 'Milk powder',
    instructions: 'Seal properly after opening.',
  },
  {
    id: 'amavuta-ya-flira',
    name: 'Amavuta ya flira',
    category: 'Cooking Essentials',
    subcategory: 'Cooking oil',
    price: 18000,
    size: 'Household bottle',
    badge: 'Daily Use',
    image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A household oil bottle prepared for daily cooking, frying, and meal prep.',
    benefits: ['Good for daily meals', 'Simple storage', 'Budget-conscious kitchen item'],
    ingredients: 'Vegetable oil',
    instructions: 'Keep capped and stored in a cool place.',
  },
  {
    id: 'vin-de-messe',
    name: 'Vin de messe',
    category: 'Wines & Spirits',
    subcategory: 'Wine',
    price: 18000,
    size: 'Bottle',
    badge: 'Ceremony Choice',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A bottle selected for ceremonies, gatherings, and intentional gift purchases.',
    benefits: ['Classic wine presentation', 'Easy to gift', 'Suitable for formal occasions'],
    ingredients: 'Red wine',
    instructions: 'Serve at a cool room temperature.',
  },
  {
    id: 'vin-de-mes',
    name: 'Vin de Mes',
    category: 'Wines & Spirits',
    subcategory: 'Wine',
    price: 16000,
    size: 'Bottle',
    badge: 'Good Value',
    image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A value-friendly wine bottle for everyday hosting and easy shelf appeal.',
    benefits: ['Accessible price point', 'Simple to pair with meals', 'Good store staple'],
    ingredients: 'Wine blend',
    instructions: 'Best enjoyed slightly chilled.',
  },
  {
    id: 'france-lait',
    name: 'France lait',
    category: 'Milk & Baby',
    subcategory: 'Infant formula',
    price: 15000,
    size: 'Tin',
    badge: 'Baby Care',
    image: 'https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'Infant formula stock selected for parents who need a dependable baby shelf option.',
    benefits: ['Convenient tin format', 'Easy shelf storage', 'Popular baby-care category'],
    ingredients: 'Infant formula',
    instructions: 'Follow the preparation directions on the package.',
  },
  {
    id: 'vin-rouge',
    name: 'Vin rouge',
    category: 'Wines & Spirits',
    subcategory: 'Red wine',
    price: 15000,
    size: 'Bottle',
    badge: 'Red Wine',
    image: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A red wine bottle suited for dinner tables, gifts, and evening hosting.',
    benefits: ['Classic presentation', 'Easy pairing with meals', 'Useful event bottle'],
    ingredients: 'Red wine',
    instructions: 'Allow a few minutes to breathe before serving.',
  },
  {
    id: 'baro-d-allemagne',
    name: "Baro d' allemagne",
    category: 'Wines & Spirits',
    subcategory: 'Imported bottle',
    price: 15000,
    size: 'Bottle',
    badge: 'Imported Feel',
    image: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'An imported-style shelf option aimed at customers shopping for a refined bottle.',
    benefits: ['Good gift look', 'Shelf appeal', 'Easy premium upsell'],
    ingredients: 'Wine or spirit blend',
    instructions: 'Ask in-store for tasting guidance.',
  },
  {
    id: 'four-cousin',
    name: 'Four cousin',
    category: 'Wines & Spirits',
    subcategory: 'Wine',
    price: 15000,
    size: 'Bottle',
    badge: 'Popular Wine',
    image: 'https://images.unsplash.com/photo-1516594915697-87eb3b1c14ea?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A familiar wine choice for relaxed hosting, gifting, and weekend purchase.',
    benefits: ['Friendly everyday option', 'Easy to share', 'Recognizable wine category'],
    ingredients: 'Wine blend',
    instructions: 'Chill if preferred before serving.',
  },
  {
    id: 'chivalac-vin-rouge',
    name: 'Chivalac vin rouge',
    category: 'Wines & Spirits',
    subcategory: 'Red wine',
    price: 15000,
    size: 'Bottle',
    badge: 'Hosting Pick',
    image: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A red wine shelf line chosen for smooth hosting and dependable presentation.',
    benefits: ['Great dinner-table option', 'Good bottle profile', 'Useful for events'],
    ingredients: 'Red wine',
    instructions: 'Store upright in a cool room.',
  },
  {
    id: 'cow-and-gate',
    name: 'Cow and gate',
    category: 'Milk & Baby',
    subcategory: 'Infant formula',
    price: 14500,
    size: 'Tin',
    badge: 'Baby Formula',
    image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A trusted baby-care shelf category designed for quick parent pick-up and restock.',
    benefits: ['Parent-focused item', 'Compact shelf size', 'Simple grab-and-go format'],
    ingredients: 'Infant formula',
    instructions: 'Use only as directed on the pack.',
  },
  {
    id: 'umushonjyi-muto',
    name: 'Umushonjyi muto',
    category: 'Beer & Cider',
    subcategory: 'Beer',
    price: 14500,
    size: 'Small bottle pack',
    badge: 'Small Format',
    image: 'https://images.unsplash.com/photo-1571767454098-246b94fbcf70?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A smaller-format beer option for lighter purchase sizes and quick take-away.',
    benefits: ['Compact pack size', 'Good for smaller orders', 'Easy to chill'],
    ingredients: 'Malted beverage',
    instructions: 'Serve chilled.',
  },
  {
    id: 'mami-love-big',
    name: 'Mami love big',
    category: 'Milk & Baby',
    subcategory: 'Diapers',
    price: 14000,
    size: 'Large pack',
    badge: 'Baby Essentials',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A large diaper pack designed for parents shopping for value and convenience.',
    benefits: ['Large pack size', 'Useful family staple', 'Easy restock item'],
    ingredients: 'Disposable diapers',
    instructions: 'Choose the right baby size before purchase.',
  },
  {
    id: 'nido-ntoya',
    name: 'Nido ntoya',
    category: 'Milk & Baby',
    subcategory: 'Milk powder',
    price: 14000,
    size: 'Small tin',
    badge: 'Small Tin',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&w=900&q=90',
    extraImages: [],
    description: 'A smaller Nido shelf size for quick household restock and budget-friendly buying.',
    benefits: ['Compact format', 'Easy to store', 'Useful for smaller households'],
    ingredients: 'Milk powder',
    instructions: 'Close the lid tightly after opening.',
  },
];
